-- MULTI TABLE ANALYSIS ON CLASSIC MODEL --

# 1. Find the total number of orders placed by each customer along with their customer name.
select c.customerNumber,c.customerName, count(orderNumber) as total_orders from orders o
join customers c on c.customerNumber=o.customerNumber
group by customerNumber
order by total_orders desc;

# 2. Which customers have placed orders but have never made a payment?
select c.customerName,c.customerNumber from customers c
join orders o on o.customerNumber=c.customerNumber
left join payments p on o.customerNumber=p.customerNumber
where p.customerNumber is null;
-- there is no customer which placed an order but did not make any payments

# 3. List customers who made payments but never placed an order.
select p.customerNumber,c.customerName from payments p
left join orders o on p.customerNumber=o.customerNumber
join customers c on c.customerNumber=p.customerNumber
where o.customerNumber is null;
-- there is no customer who made payment but did not ordered.

# 4. Find the average time taken to ship orders for each customer.
select c.customerNumber ,c.customerName, avg(datediff(shippedDate,orderDate))as avg_time,count(o.customerNumber) as total_orders from orders o
join customers c on o.customerNumber=c.customerNumber
group by o.customerNumber
order by avg_time desc;

# 5. Identify customers with the highest payment amounts and their corresponding sales reps.
select c.customerName,e.firstName as employee_name,sum(amount) as total_value from payments p
join customers c on p.customerNumber=c.customerNumber
join employees e on c.salesRepEmployeeNumber=e.employeeNumber
group by p.customerNumber
order by total_value desc;

# 6. Which customers have exceeded their credit limit when considering total order value vs credit limit?
select *,total_price-creditLimit as difference from (
select  sum((od.quantityOrdered*od.priceEach)) as total_price,c.customerNumber,c.creditLimit
from orderdetails od
join orders o on od.orderNumber = o.orderNumber
join customers c on c.customerNumber = o.customerNumber
join employees e on e.employeeNumber = c.salesRepEmployeeNumber
where o.status='shipped'
group by c.customerNumber
having total_price>creditLimit) t
order by difference desc;

# 7. Find the top 5 customers by total order value (from orderdetails) and compare with their total payments.
select *, (total_order - total_payment) as due from(
select od.orderNumber,sum((quantityOrdered*priceEach))as total_order,sum(amount) as total_payment from orderdetails od
join orders o on od.orderNumber=o.orderNumber
join customers c on c.customerNumber=o.customerNumber
join payments p on p.customerNumber=c.customerNumber
group by c.customerNumber) t
order by due asc;

# 8. List all orders that were shipped late along with the customer name and sales rep.
select o.orderNumber,c.customerName,e.firstName from orders o
join customers c on c.customerNumber = o.customerNumber
join employees e on e.employeeNumber = c.salesRepEmployeeNumber
where shippedDate>requiredDate;

# 9. Which employees manage the customers with the highest total payments?
select c.customerName,e.firstName,od.orderNumber,sum(priceEach*quantityOrdered) as total_value from orderdetails od
join orders o on o.orderNumber=od.orderNumber
join customers c on o.customerNumber=c.customerNumber
join employees e on e.employeeNumber=c.salesRepEmployeeNumber
group by od.orderNumber
order by total_value desc
limit 10;

# 10. Show the employees and their customers who have never placed an order.
select c.customerNumber,c.customerName,e.firstName from orders o
right join customers c on c.customerNumber=o.customerNumber
join employees e on c.salesRepEmployeeNumber=e.employeeNumber
where o.orderNumber is null;

# 11. Find the product lines with the highest total sales revenue.
# 12. List the top 10 best-selling products (by quantity ordered) across all customers.
# 13. Which products are ordered most frequently together in the same order?
# 14. For each product, calculate average order quantity and compare with available stock.
# 15. Identify products that have never been ordered.
# 16. Find the total revenue generated per product line per year.
# 17. Which product lines generate the most revenue in each office territory?
# 18. Compare MSRP and average selling price for each product (from orderdetails).
# 19. Identify products sold below MSRP and calculate the total loss.
# 20. Which products generated the highest revenue for each customer?

# 21. Show the number of orders and average shipping delay for each office location.
# 22. Identify offices where average shipping delay is higher than the global average.
# 23. Find the office with the highest number of customers.
# 24. Which employees from each office handle the most high-value customers?
# 25. For each office, calculate total sales revenue generated by its employees.

# 26. List all employees along with the number of customers they manage and total revenue generated.
# 27. Find employees who manage customers but whose customers have never made a payment.
# 28. Identify employees with the highest total payments from their customers.
# 29. Which employees are managing customers with overdue orders?
# 30. Find the reporting hierarchy: employees with their managers and total sales handled under them.

# 31. Compare monthly total orders with monthly total payments to check consistency.
# 32. Identify months where total payments < total order value (potential overdue).
# 33. Calculate average order size (in revenue) per month and track trend over time.
# 34. Which months have the highest shipping delays?
# 35. Find correlation between order value and shipping delay.

# 36. For each customer, calculate their lifetime value (total order revenue - total payments).
# 37. Identify high-value customers who have not placed any recent orders (last 1 year).
# 38. Show customers whose orders are frequently shipped late and their sales rep.
# 39. Calculate total sales per customer per year and identify year-over-year growth.
# 40. Find the top 3 customers in each country by total revenue.

# 41. Which customers placed orders across multiple product lines?
# 42. For each product line, find the customer who contributed the most revenue.
# 43. Identify product lines with declining sales over time.
# 44. Find the average number of different products ordered per order by each customer.
# 45. Identify customers who ordered every product line at least once.

# 46. Compare the payment behavior (average payment delay if simulated) by country.
# 47. Which countries contribute the most revenue vs most number of orders?
# 48. Find the customer in each country with the largest order placed.
# 49. Compare revenue per office territory across different years.
# 50. Identify regions with the most late shipments.

# 51. Find orders where total payment amount is less than total order value.
# 52. Identify customers who frequently underpay (payments < order totals).
# 53. Which employees have the most underpaying customers?
# 54. For each order, calculate profit margin (MSRP - buyPrice) * quantity.
# 55. Find the top 5 most profitable products.

# 56. Show trend of total payments over the years and compare with total orders.
# 57. Which year had the highest growth in number of customers?
# 58. Find year-over-year growth rate of revenue.
# 59. Compare late shipment percentage across years.
# 60. Identify products whose sales increased significantly year-over-year.

# 61. Find the total number of orders and payments for each sales rep.
# 62. Identify sales reps who manage customers with the highest average order size.
# 63. For each sales rep, find their customers who consistently order late.
# 64. Compare sales performance between employees reporting to the same manager.
# 65. Rank sales reps based on total revenue they generated.

# 66. Find the distribution of payment amounts (small, medium, large) across customers.
# 67. Identify customers who mostly make small payments but place large orders.
# 68. For each customer, calculate payment-to-order ratio.
# 69. Which customers made the largest single payment and which sales rep managed them?
# 70. Compare total payments by payment method (if checkNumber indicates type).

# 71. For each order, calculate delay = shippedDate - requiredDate.
# 72. Find customers with the highest average delay across their orders.
# 73. Identify orders that were shipped before the required date.
# 74. Compare shipping performance across offices.
# 75. Find the product most often included in late orders.

# 76. Identify customers who paid more than their total order amount (overpayment).
# 77. Find all orders without corresponding payments (unpaid orders).
# 78. Which products are most commonly ordered in unpaid/underpaid orders?
# 79. Identify employees with the highest unpaid orders under their customers.
# 80. Compare unpaid orders across different years.

# 81. For each product line, show revenue contribution % to the company.
# 82. Identify the least profitable product line each year.
# 83. Find customers who only order from a single product line.
# 84. Which product lines are most popular in each country?
# 85. Show trend of product line sales across years.

# 86. List employees with no customers assigned.
# 87. Find customers who are not assigned to any employee (sales rep).
# 88. Identify customers linked to sales reps who left (if reportsTo is null).
# 89. Show hierarchy of employees with total sales under them.
# 90. Compare managers’ team performance (sum of sales).

# 91. For each country, calculate number of customers and total revenue.
# 92. Identify customers with the most frequent orders per year.
# 93. Find customers who have reduced their order frequency over the years.
# 94. Show average revenue per customer in each country.
# 95. Compare customer growth across countries.

# 96. For each product, find how many unique customers ordered it.
# 97. Identify products that are ordered by only one customer.
# 98. Find customers who ordered the widest variety of products.
# 99. For each product line, show the average order size (quantity).
# 100. Identify products frequently included in high-value orders (> $10,000).
